[package]
name = "raw-dog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
esp32c3-hal = { git = "https://github.com/esp-rs/esp-hal.git", features = ["ufmt"] }
riscv-rt = "0.8"
panic-halt = "0.2"
